name: 'Errors form Unity log file'
description: 'Outputs Unity errors to github summary'
author: 'Maxim Matveev'
inputs:
  logFile:
    description: 'Unity log file'
    required: true
outputs:
  result: # release id
    description: 'Release id'    
runs:
  using: 'docker'
  image: 'Dockerfile'
